import { motion } from "framer-motion";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import BackgroundOrbs from "@/components/BackgroundOrbs";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-background relative selection:bg-blue-500/30 font-inter">
      <BackgroundOrbs />
      <Navbar />
      
      <main className="container mx-auto px-6 pt-32 pb-20 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="max-w-4xl mx-auto"
        >
          <div className="mb-12">
            <h1 className="font-play text-4xl md:text-5xl font-bold text-white mb-4">
              Privacy <span className="gradient-text">Policy</span>
            </h1>
            <p className="font-play text-white/40 text-sm">Last updated: March 26, 2026</p>
          </div>

          <div className="glass-card p-8 md:p-12 space-y-8 text-white/70 leading-relaxed border-white/5 text-sm md:text-base">
            <section className="space-y-4">
              <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
              <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                <span className="w-1.5 h-8 bg-blue-500 rounded-full" />
                Interpretation and Definitions
              </h2>
              
              <div className="space-y-4">
                <h3 className="text-xl font-semibold text-white/90 underline decoration-blue-500/30 underline-offset-4">Interpretation</h3>
                <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                
                <h3 className="text-xl font-semibold text-white/90 underline decoration-blue-500/30 underline-offset-4">Definitions</h3>
                <p>For the purposes of this Privacy Policy:</p>
                <ul className="list-disc pl-6 space-y-4 marker:text-blue-500">
                  <li><p><strong className="text-white">Account</strong> means a unique account created for You to access our Service or parts of our Service.</p></li>
                  <li><p><strong className="text-white">Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p></li>
                  <li><p><strong className="text-white">Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to BluOrbit Tech, 845 S Windsor Blvd, Los Angeles, CA 90005 United States.</p></li>
                  <li><p><strong className="text-white">Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p></li>
                  <li><p><strong className="text-white">Country</strong> refers to: California, United States</p></li>
                  <li><p><strong className="text-white">Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p></li>
                  <li><p><strong className="text-white">Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.</p></li>
                  <li><p><strong className="text-white">Service</strong> refers to the Website.</p></li>
                  <li><p><strong className="text-white">Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p></li>
                  <li><p><strong className="text-white">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p></li>
                  <li><p><strong className="text-white">Website</strong> refers to BluOrbitTech, accessible from BluOrbitTech.com.</p></li>
                  <li><p><strong className="text-white">You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p></li>
                </ul>
              </div>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                <span className="w-1.5 h-8 bg-blue-500 rounded-full" />
                Collecting and Using Your Personal Data
              </h2>
              
              <div className="space-y-4">
                <h3 className="text-xl font-semibold text-white/90 underline decoration-blue-500/30 underline-offset-4">Types of Data Collected</h3>
                
                <h4 className="text-lg font-medium text-white italic">Personal Data</h4>
                <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul className="list-disc pl-6 space-y-2 marker:text-blue-500">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address, State, Province, ZIP/Postal code, City</li>
                </ul>

                <h4 className="text-lg font-medium text-white italic pt-4">Usage Data</h4>
                <p>Usage Data is collected automatically when using the Service.</p>
                <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                
                <h4 className="text-lg font-medium text-white italic pt-4">Tracking Technologies and Cookies</h4>
                <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
                <ul className="list-disc pl-6 space-y-4 marker:text-blue-500">
                  <li><p><strong className="text-white">Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p></li>
                  <li><p><strong className="text-white">Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages or opened an email and for other related website statistics.</p></li>
                </ul>
              </div>
            </section>

            <section className="space-y-6">
              <h3 className="text-xl font-semibold text-white/90">Use of Your Personal Data</h3>
              <p>The Company may use Personal Data for the following purposes:</p>
              <ul className="list-disc pl-6 space-y-4 marker:text-blue-500">
                <li><p><strong className="text-white">To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p></li>
                <li><p><strong className="text-white">To manage Your Account:</strong> to manage Your registration as a user of the Service.</p></li>
                <li><p><strong className="text-white">For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for products or services.</p></li>
                <li><p><strong className="text-white">To contact You:</strong> By email, telephone, SMS, or equivalent electronic communication regarding updates or informative communications.</p></li>
                <li><p><strong className="text-white">To provide You</strong> with news, special offers, and general information about other goods, services and events.</p></li>
                <li><p><strong className="text-white">To manage Your requests:</strong> To attend and manage Your requests to Us.</p></li>
              </ul>
            </section>

            <section className="space-y-6">
              <h3 className="text-xl font-semibold text-white/90 underline decoration-blue-500/30 underline-offset-4">Retention of Your Personal Data</h3>
              <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations.</p>
              <p>Account Information for User Accounts is retained for the duration of your account relationship plus up to 24 months after account closure.</p>
            </section>

            <section className="space-y-6">
              <h3 className="text-xl font-semibold text-white/90 underline decoration-blue-500/30 underline-offset-4">Security of Your Personal Data</h3>
              <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
            </section>

            <section className="space-y-6">
              <h2 className="text-2xl font-bold text-white flex items-center gap-3">
                <span className="w-1.5 h-8 bg-blue-500 rounded-full" />
                Contact Us
              </h2>
              <p>If you have any questions about this Privacy Policy, You can contact us:</p>
              <ul className="list-disc pl-6 space-y-2 marker:text-blue-500">
                <li>By email: <a href="mailto:hello@bluorbittech.com" className="text-blue-400 hover:text-blue-300 transition-colors">hello@bluorbittech.com</a></li>
              </ul>
            </section>
          </div>
        </motion.div>
      </main>

      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
